In [ ]:
import pandas as pd

In [ ]:
data={
    "product": ["shoes", "tshirt","phone", "laptop","watch", "bag", "tablet"],
    "category":["fashion", "fashion","electronics","electronics","accessories","fashion","electronics"],
    "price":[2000, 800, 15000, 55000,3000,1200,20000],
    "rating": [4.5,4.2, 4.7, 4.8, 4.3, 4.1, 4.6],
    "stock":[20,50,15,8,30,40,10]
}
df=pd.DataFrame(data)
print(df)

  product     category  price  rating  stock
0   shoes      fashion   2000     4.5     20
1  tshirt      fashion    800     4.2     50
2   phone  electronics  15000     4.7     15
3  laptop  electronics  55000     4.8      8
4   watch  accessories   3000     4.3     30
5     bag      fashion   1200     4.1     40
6  tablet  electronics  20000     4.6     10

In [ ]:
print(df.head())
print(df.shape)
print(df.columns)
df.info()

  product     category  price  rating  stock
0   shoes      fashion   2000     4.5     20
1  tshirt      fashion    800     4.2     50
2   phone  electronics  15000     4.7     15
3  laptop  electronics  55000     4.8      8
4   watch  accessories   3000     4.3     30
(7, 5)
Index(['product', 'category', 'price', 'rating', 'stock'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   7 non-null      object
 1   category  7 non-null      object
 2   price     7 non-null      int64
 3   rating    7 non-null      float64
 4   stock     7 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 412.0+ bytes

In [ ]:
print("Average price of the products: ",df["price"].mean())
print("Highest price product: ",df[df["price"]==df["price"].max()])
print("Products with price greater than 10000:\n",df[df["price"]>10000])
df[["product","price"]]

Average price of the products:  13857.142857142857
Highest price product:    product     category  price  rating  stock
3  laptop  electronics  55000     4.8      8
Products with price greater than 10000:
   product     category  price  rating  stock
2   phone  electronics  15000     4.7     15
3  laptop  electronics  55000     4.8      8
6  tablet  electronics  20000     4.6     10

  product  price
0   shoes   2000
1  tshirt    800
2   phone  15000
3  laptop  55000
4   watch   3000
5     bag   1200
6  tablet  20000

In [ ]:
print(df.groupby("category")["price"].mean())
print(df.groupby("category")["product"].count())
print(df.groupby("category")["rating"].mean())
df.groupby("category")["stock"].sum()

category
accessories     3000.000000
electronics    30000.000000
fashion         1333.333333
Name: price, dtype: float64
category
accessories    1
electronics    3
fashion        3
Name: product, dtype: int64
category
accessories    4.300000
electronics    4.700000
fashion        4.266667
Name: rating, dtype: float64

category
accessories     30
electronics     33
fashion        110
Name: stock, dtype: int64

In [ ]:
print(df.sort_values("price", ascending=False))
print(df.sort_values("rating",ascending=False).head(3))
df.loc[df["price"].idxmin()]

  product     category  price  rating  stock
3  laptop  electronics  55000     4.8      8
6  tablet  electronics  20000     4.6     10
2   phone  electronics  15000     4.7     15
4   watch  accessories   3000     4.3     30
0   shoes      fashion   2000     4.5     20
5     bag      fashion   1200     4.1     40
1  tshirt      fashion    800     4.2     50
  product     category  price  rating  stock
3  laptop  electronics  55000     4.8      8
2   phone  electronics  15000     4.7     15
6  tablet  electronics  20000     4.6     10

product      tshirt
category    fashion
price           800
rating          4.2
stock            50
Name: 1, dtype: object

In [ ]:
print("Most expensive product:",df.loc[df["price"].idxmax(),"product"])
print("Cheapest product:",df.loc[df["price"].idxmin(),"product"])
print("Best rated product:", df.loc[df["rating"].idxmax(),"product"])
print("category with highest average price:",df.groupby("category")["price"].mean().idxmax())
print("Category with highest average rating:",df.groupby("category")["rating"].mean().idxmax())

Most expensive product: laptop
Cheapest product: tshirt
Best rated product: laptop
category with highest average price: electronics
Category with highest average rating: electronics

In [ ]:
print("Total stock available:",df["stock"].sum())
print("Product with lowest stock:\n",df.loc[df["stock"].idxmin(),"product"])
print("Product with stock less than 15:\n",df[df["stock"]<15])
print("Average stock per category:\n",df.groupby("category")["stock"].mean())

Total stock available: 173
Product with lowest stock:
 laptop
Product with stock less tha 15:
   product     category  price  rating  stock
3  laptop  electronics  55000     4.8      8
6  tablet  electronics  20000     4.6     10
Average stock per category:
 category
accessories    30.000000
electronics    11.000000
fashion        36.666667
Name: stock, dtype: float64

In [ ]:
print("Product priced above average price:\n",df[df["price"]>df["price"].mean()])
print("Products with rating greater than 4.5:\n",df[df["rating"]>4.5])
print("Electronics products only:\n",df[df["category"] == "electronics"])
print("Fashion products priced above 1000:\n",df[(df["category"]=="fashion") & (df["price"]>1000)])

Product priced above average price:
   product     category  price  rating  stock
2   phone  electronics  15000     4.7     15
3  laptop  electronics  55000     4.8      8
6  tablet  electronics  20000     4.6     10
Products with rating greater than 4.5:
   product     category  price  rating  stock
2   phone  electronics  15000     4.7     15
3  laptop  electronics  55000     4.8      8
6  tablet  electronics  20000     4.6     10
Electronics products only:
   product     category  price  rating  stock
2   phone  electronics  15000     4.7     15
3  laptop  electronics  55000     4.8      8
6  tablet  electronics  20000     4.6     10
Fashion products priced above 1000:
   product category  price  rating  stock
0   shoes  fashion   2000     4.5     20
5     bag  fashion   1200     4.1     40

In [ ]:
print("Top 3 expensive products:\n",df.sort_values("price",ascending=False).head(3))
print("Top 3 highest rated products:\n",df.sort_values("rating",ascending=False).head(3))
print("Sorting products by stock in descending order:\n",df.sort_values("stock",ascending=False))
df["value_score"]=df["rating"]* df["price"]
print(df)

Top 3 expensive products:
   product     category  price  rating  stock  value_score
3  laptop  electronics  55000     4.8      8     264000.0
6  tablet  electronics  20000     4.6     10      92000.0
2   phone  electronics  15000     4.7     15      70500.0
Top 3 highest rated products:
   product     category  price  rating  stock  value_score
3  laptop  electronics  55000     4.8      8     264000.0
2   phone  electronics  15000     4.7     15      70500.0
6  tablet  electronics  20000     4.6     10      92000.0
Sorting products by stock in descending order:
   product     category  price  rating  stock  value_score
1  tshirt      fashion    800     4.2     50       3360.0
5     bag      fashion   1200     4.1     40       4920.0
4   watch  accessories   3000     4.3     30      12900.0
0   shoes      fashion   2000     4.5     20       9000.0
2   phone  electronics  15000     4.7     15      70500.0
6  tablet  electronics  20000     4.6     10      92000.0
3  laptop  electronics  55000     4.8      8     264000.0
  product     category  price  rating  stock  value_score
0   shoes      fashion   2000     4.5     20       9000.0
1  tshirt      fashion    800     4.2     50       3360.0
2   phone  electronics  15000     4.7     15      70500.0
3  laptop  electronics  55000     4.8      8     264000.0
4   watch  accessories   3000     4.3     30      12900.0
5     bag      fashion   1200     4.1     40       4920.0
6  tablet  electronics  20000     4.6     10      92000.0

In [ ]:
print("Best value product:",df.sort_values("value_score",ascending=False).head(1))

Best value product:   product     category  price  rating  stock  value_score
3  laptop  electronics  55000     4.8      8     264000.0